---
- hosts: webservers
  remote_user: root

  tasks:
    - name: create some files
      file: name=/data/{{ item }} state=touch
      when: ansible_distribution_major_version == "7"
      with_items:
        - file1
        - file2
        - file3
    
    - name: install some packages
      yum: name={{ item }}
      with_items:
        - htop
        - sl
        - hping3


   